make deploy commands less verbose

diff --git a/commands/deploy b/commands/deploy
--- a/commands/deploy
+++ b/commands/deploy
@@ -51,10 +51,17 @@ if [ -n "$dirty" ]; then
   exit 1
 fi;
 
+if ! git ls-remote --heads --exit-code origin $branch > /dev/null; then
+  echo "Branch $branch not found"
+  exit 1
+fi;
+
+echo "Starting deploy of $app to $appEnv on branch $branch" 
+
 # fetch any new branches
 git fetch --all --quiet
 # switch to branch
-git checkout $branch --quiet 
+git checkout $branch --quiet > /dev/null 2>&1
 # update to state of remote branch
 git reset --hard origin/$branch --quiet 
 
@@ -65,6 +72,7 @@ bundle check > /dev/null || bundle install > /dev/null
 
 # do not exit if deploy command fails
 set +o errexit
+# run cap, saving output to logfile
 # return exit code of first command
 # http://stackoverflow.com/questions/1221833/bash-pipe-output-and-capture-exit-status
 deploy=$(bundle exec cap $appEnv deploy 2>&1 | tee -a $logFile; exit ${PIPESTATUS[0]})
@@ -73,7 +81,7 @@ deployStatus=$?
 echo "Log saved to: $logFile"
 
 if [ $deployStatus -ne 0 ]; then
-  echo "Error deploying"
+  echo "Error deploying, see $logFile"
   exit 1
 fi;
 
